const constants = {
    SET_TIME: "SET_TIME",

	ALL_RIDERS: "ALL_RIDERS",
	ALL_POSITIONS: "ALL_POSITIONS",
	ALL_TEAMS: "ALL_TEAMS",

	ADD_RIDER: "ADD_RIDER",

	TEAM_ADD_RIDER: "TEAM_ADD_RIDER",

	SET_ACTIVE_RIDER: "SET_ACTIVE_RIDER",

	RESULT_ADD_TIME: "RESULT_ADD_TIME",

	RIDER_LEFT: "RIDER_LEFT",
	RIDER_RIGHT: "RIDER_RIGHT",
	RIDER_FASTER: "RIDER_FASTER"
}

export default constants